-- Migration 014: Add auto-generated flag to links table
-- This allows us to distinguish between user-created links and Teed auto-generated links

-- Add is_auto_generated column to links table
ALTER TABLE links
ADD COLUMN IF NOT EXISTS is_auto_generated boolean DEFAULT false NOT NULL;

-- Add comment explaining the column
COMMENT ON COLUMN links.is_auto_generated IS 'True if this link was auto-generated by Teed product search, false if user-created';

-- Create index for filtering auto-generated links
CREATE INDEX IF NOT EXISTS idx_links_auto_generated ON links(is_auto_generated);

-- RLS policies remain unchanged (user-created and auto-generated links have same access controls)
